### ISSUE TITLE
!profile does not work when you provide it with a raw ID

### ISSUE THREAD

**Issue by wakfi** [SSwiftGamer440/Admin-Bot#2]
I give it a raw ID number and it doesn't work

**Comment by wakfi** [comment]
This is not a bug this is a feature request

**Comment by wakfi** [comment]
We are going to revisit this request

**Comment by SSwiftGamer440** [comment]
DENY: Feature Request, Already on list as P1, Fix Quickly, Closing

**Comment by wakfi** [comment]
Close it once the issue is actually fixed lmao
